import OpenAI from "openai";
import { logger } from "./logger";

function getClient(): OpenAI {
  return new OpenAI({
    baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  });
}

export interface ScriptOutput {
  topic: string;
  hook: string;
  script: string;
  cta: string;
  caption: string;
  hashtags: string;
  estimated_duration_seconds: number;
}

export async function generateScript(
  topic: string,
  niche: string,
  tone: string,
  language: string,
  durationSeconds: number
): Promise<ScriptOutput> {
  const client = getClient();
  const wordCount = Math.round((durationSeconds / 60) * 130); // ~130 wpm for video

  const prompt = `Eres un experto en creación de contenido para Instagram Reels.

IMPORTANTE: Usa español neutro (sin voseo, sin modismos regionales). Tutea al espectador ("tú", "te", "tu"), no uses "vos" ni conjugaciones del voseo como "seguime", "guardá", "comentá", "hacé". El contenido debe ser comprensible para cualquier hispanohablante.

Crea un guion de video para un Reel de Instagram con estas especificaciones:
- Nicho: ${niche}
- Tema: ${topic}
- Tono: ${tone}
- Idioma: ${language}
- Duración aproximada: ${durationSeconds} segundos (~${wordCount} palabras)

REGLAS OBLIGATORIAS para el campo "script":
1. El guion DEBE terminar con una llamada a la acción clara y directa hablada por el avatar (ej: "Sígueme para más tips como este", "Guarda este video y ponlo en práctica hoy", "Comenta abajo si te pasó esto").
2. La ÚLTIMA oración del guion SIEMPRE debe ser una de estas frases — elige UNA distinta cada vez (varía, no repitas siempre la misma):
   - "Sígueme y te enseño a crear un avatar de inteligencia artificial como este."
   - "¿Te imaginas tener tu propio avatar de inteligencia artificial? Sígueme y te cuento cómo."
   - "Soy un avatar creado con inteligencia artificial. Sígueme y aprende a crear el tuyo."
   - "Esto que ves es inteligencia artificial en acción. Sígueme y descubre cómo usarla en tu negocio."
   - "Si te preguntas cómo se hace esto, sígueme — te explico todo sobre los avatares de inteligencia artificial."
   - "Todo lo que ves en este video es inteligencia artificial. Sígueme para aprender a usarla tú también."
   - "Soy un avatar digital generado con inteligencia artificial. Sígueme para más contenido como este."
   - "Este video fue creado con inteligencia artificial. Sígueme y te ayudo a crear algo así para tu negocio."
3. El hook debe ser la primera frase del guion (ya incluida dentro de "script").
4. Sin indicaciones de escena, sin corchetes, sin asteriscos — solo texto hablado corrido.
5. El tono debe sentirse conversacional, no como un comercial.
6. NUNCA uses abreviaturas que el avatar leería mal: escribe "inteligencia artificial" (no "IA" ni "AI"), "retorno de inversión" (no "ROI"), "indicadores clave" (no "KPIs"), "director ejecutivo" (no "CEO"), etc. — todo debe sonar natural cuando se lee en voz alta.
7. NUNCA uses diminutivos, jerga o frases incompletas. Las oraciones deben ser completas y claras para que el avatar las lea correctamente.

Devuelve SOLO un JSON válido con esta estructura exacta:
{
  "hook": "Primera frase gancho (primeros 3 segundos, que detenga el scroll)",
  "script": "El guion completo que leerá el avatar. Debe incluir: hook al inicio → desarrollo → CTA hablado → divulgación IA al final.",
  "cta": "La llamada a la acción principal (la misma que está dentro del script, extraída aquí brevemente)",
  "caption": "Caption para Instagram (2-3 oraciones atractivas que complementen el video)",
  "hashtags": "#hashtag1 #hashtag2 #hashtag3 (10-15 hashtags relevantes y específicos al tema)",
  "estimated_duration_seconds": ${durationSeconds}
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as Omit<ScriptOutput, "topic">;
  logger.info({ topic }, "Script generated by AI");
  return { topic, ...parsed };
}

export interface RegenerateCaptionOutput {
  caption: string;
  hashtags: string;
}

export async function regenerateCaption(
  topic: string,
  script: string,
  niche: string,
  tone: string,
  language: string
): Promise<RegenerateCaptionOutput> {
  const client = getClient();

  const prompt = `Eres un experto en copywriting para Instagram Reels. Tu trabajo es escribir la descripción del post (caption) para acompañar el video.

Nicho: ${niche}
Tono: ${tone}
Idioma: ${language}
Tema: ${topic}

Guion del video (úsalo como base para que el caption esté directamente relacionado con lo que dice el video):
"""
${script}
"""

REGLAS ESTRICTAS:
1. El caption debe tener 3-5 oraciones. Primera oración: hook que llame la atención y haga querer ver el video (puede empezar con emoji). Segunda/tercera: complementa o amplía lo más valioso del video. Última oración OBLIGATORIA: un llamado a la acción claro y específico (ej: "Guardá este video para cuando lo necesites 📌", "Seguime para más tips como este", "Comentá 👇 si ya lo usabas", "Compartí esto con alguien que lo necesite").
2. Usa español neutro (tutea con "tú" o imperativos directos, nunca "vos" ni voseo).
3. El caption debe sentirse escrito por una persona real, no por una IA.
4. Los hashtags: 10-15, mezcla entre específicos al tema (alcance medio) y amplios (#ia, #emprendedores, etc). Sin espacios entre ellos.

Devuelve SOLO un JSON válido con esta estructura exacta:
{
  "caption": "...",
  "hashtags": "#tag1 #tag2 #tag3 ..."
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as RegenerateCaptionOutput;
  logger.info({ topic }, "Caption regenerated by AI");
  return parsed;
}

export interface ContentPlanTopic {
  topic: string;
  scheduled_at: string;
}

// Topic categories and hook formats for high-performing Reels content
const TOPIC_CATEGORIES = `
MEZCLA DE CONTENIDO (proporciones aproximadas):
  - 30% GANCHO EMOCIONAL: frustraciones reales, errores costosos, miedos del nicho
  - 25% REVELACIÓN: algo que la audiencia no sabe o cree equivocado
  - 25% RESULTADO CONCRETO: caso real, número específico, transformación visible
  - 20% TENDENCIA URGENTE: algo que cambia ahora y afecta al nicho

FORMATOS DE TÍTULO — rota entre todos estos, NUNCA uses el mismo formato más de 2 veces en el mismo plan:
  A) Pregunta provocadora:     "¿Por qué [problema que todos tienen pero nadie admite]?"
  B) Error costoso:            "El error que [consecuencia negativa concreta] — y cómo evitarlo"
  C) Dato que sorprende:       "[Número o porcentaje] de [audiencia] [hecho inesperado] — aquí por qué"
  D) Revelación:               "Lo que [plataforma/empresa famosa] no quiere que sepas sobre [X]"
  E) Contraintuitivo:          "Dejar de [hacer X] fue lo mejor que hice para [resultado del nicho]"
  F) Caso real sin nombre:     "De [estado inicial] a [resultado] en [tiempo] — sin [recurso que la gente cree necesitar]"
  G) Urgencia de tendencia:    "[Plataforma] acaba de cambiar [cosa específica] — esto te afecta si [descripción audiencia]"
  H) Desmitificación:          "No necesitas [cosa cara/compleja] para [resultado deseado] — esto es lo que sí funciona"
  I) Lista corta accionable:   "[2-4] cosas que [audiencia] hace diferente para [resultado concreto]"
  J) Provocación directa:      "Tu [X] está perdiendo dinero ahora mismo — y probablemente ni lo sabes"

REGLA CRÍTICA DE TÍTULOS:
  ❌ PROHIBIDO: títulos que empiecen con "Cómo crear", "Guía para", "Tutorial de", "Paso a paso"
  ❌ PROHIBIDO: mencionar nombres de herramientas técnicas en el título a menos que sean marcas conocidas (WhatsApp, Instagram, ChatGPT)
  ✅ OBLIGATORIO: el título debe sonar como la primera frase que diría una persona real mirando a cámara
  ✅ OBLIGATORIO: debe generar curiosidad o incomodidad en los primeros 3 segundos
`.trim();

export async function generateContentTopics(
  niche: string,
  keywords: string[],
  tone: string,
  language: string,
  days: number,
  postsPerDay: number,
  topPerformingTopics: string[] = []
): Promise<ContentPlanTopic[]> {
  const client = getClient();
  const total = days * postsPerDay;

  // Derive content pillars from the niche string so the AI spreads topics
  // evenly instead of fixating on a single keyword.
  // E.g. "Marketing digital, automatizaciones, chatbot, IA" → 4 pillars
  const rawPillars = niche
    .split(/[,;|]/)
    .map((p) => p.trim())
    .filter((p) => p.length > 2);

  // Also include extra keywords that aren't already covered by pillars
  const extraKeywords = keywords.filter(
    (k) => !rawPillars.some((p) => p.toLowerCase().includes(k.toLowerCase()))
  );
  const allPillars = [...rawPillars, ...extraKeywords];

  const maxPerPillar = Math.ceil(total / Math.max(allPillars.length, 1));

  const prompt = `Eres un estratega de contenido para Instagram Reels especializado en crecimiento orgánico.

IMPORTANTE: Usa español neutro (sin voseo, sin modismos regionales). Tutea al espectador ("tú", "te"). Todo debe sonar natural cuando lo dice un avatar en video.

Genera un plan de contenido con EXACTAMENTE ${total} temas únicos para:
- Nicho: ${niche}
- Tono: ${tone}
- Idioma: ${language}

TEMAS PROHIBIDOS — NO repetir, NO parafrasear, NO abordar el mismo ángulo:
${topPerformingTopics.slice(0, 12).join("\n") || "N/A"}

PILARES DE CONTENIDO — distribuye los ${total} temas entre estos pilares (máx ${maxPerPillar} por pilar, nunca 2 seguidos del mismo):
${allPillars.map((p, i) => `  ${i + 1}. ${p}`).join("\n")}

ÁNGULOS POSIBLES POR PILAR (varía entre ellos):
  - Problema del dueño del negocio: "el error que cometen al usar X", "por qué X les cuesta dinero sin saberlo"
  - Perspectiva del cliente final: "qué piensan tus clientes cuando X los atiende"
  - Comparativa: "X vs Y — cuál elegir según tu situación"
  - Tendencia reciente: "qué cambió en X en 2026 y cómo te afecta"
  - Resultado medible: "qué logra una empresa que usa X bien vs una que lo usa mal"
  - Desmitificación: "por qué la mayoría cree que X es difícil (y están equivocados)"

${TOPIC_CATEGORIES}

REGLA ANTI-DUPLICADOS — CRÍTICA:
  • Cada uno de los ${total} temas debe ser COMPLETAMENTE DIFERENTE en ángulo, formato y subtema
  • Si hay ${postsPerDay} videos el mismo día, sus temas deben hablar de cosas DISTINTAS (uno no puede ser la continuación del otro)
  • Antes de escribir cada título, verifica mentalmente que no coincida con ninguno anterior de la lista
  • NUNCA repitas el mismo verbo o estructura en más de 2 títulos del mismo plan

Reglas de calidad:
  • Cada título debe ser específico — evitar genéricos como "Tips de marketing" o "Consejos de IA"
  • Los temas TRENDING deben referenciar contexto real 2025-2026: cambios de algoritmo, nuevas funciones de plataformas, reportes de adopción de IA
  • Cada tema debe desarrollarse en un Reel de 45-75 segundos sin necesidad de visuals complejas
  • Los temas deben distribuirse a lo largo de ${days} días, máximo ${postsPerDay} por día

Devuelve SOLO un JSON válido:
{
  "topics": [
    {
      "topic": "Título exacto del Reel",
      "days_from_now": 0,
      "pillar": "nombre del pilar",
      "format": "letra del formato usado (A-J)",
      "category": "emocional|revelacion|resultado|tendencia"
    }
  ]
}

Genera exactamente ${total} temas distintos. Verifica la lista completa antes de responder para confirmar que no hay duplicados ni temas similares.`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as { topics: Array<{ topic: string; days_from_now: number; category?: string }> };
  const now = new Date();

  return parsed.topics.map((t) => {
    const date = new Date(now);
    date.setDate(date.getDate() + t.days_from_now);
    date.setHours(9, 0, 0, 0);
    return { topic: t.topic, scheduled_at: date.toISOString() };
  });
}

export async function analyzeAuditAndRecommend(
  niche: string,
  topPostCaptions: string[],
  avgEngagement: number,
  language: string
): Promise<{ recommended_topics: string[]; content_insights: string; best_posting_times: string[] }> {
  const client = getClient();

  const prompt = `Analiza el rendimiento de una cuenta de Instagram y genera recomendaciones.

Nicho: ${niche}
Idioma: ${language}
Engagement promedio: ${avgEngagement.toFixed(2)}%
Mejores captions/temas de los últimos posts:
${topPostCaptions.slice(0, 10).map((c, i) => `${i + 1}. ${c?.substring(0, 100) || "Sin caption"}`).join("\n")}

Devuelve SOLO un JSON válido:
{
  "recommended_topics": ["tema 1", "tema 2", "tema 3", "tema 4", "tema 5"],
  "content_insights": "2-3 oraciones con insights clave sobre qué tipo de contenido funciona mejor",
  "best_posting_times": ["09:00", "18:00", "21:00"]
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty AI response");
  return JSON.parse(content);
}
