import OpenAI from "openai";
import { logger } from "./logger";

function getClient(): OpenAI {
  return new OpenAI({
    baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  });
}

export interface ScriptOutput {
  topic: string;
  hook: string;
  script: string;
  cta: string;
  caption: string;
  hashtags: string;
  estimated_duration_seconds: number;
}

export async function generateScript(
  topic: string,
  niche: string,
  tone: string,
  language: string,
  durationSeconds: number
): Promise<ScriptOutput> {
  const client = getClient();
  const wordCount = Math.round((durationSeconds / 60) * 130); // ~130 wpm for video

  const prompt = `Eres un experto en creación de contenido para Instagram Reels.

Crea un guion de video para un Reel de Instagram con estas especificaciones:
- Nicho: ${niche}
- Tema: ${topic}
- Tono: ${tone}
- Idioma: ${language}
- Duración aproximada: ${durationSeconds} segundos (~${wordCount} palabras)

Devuelve SOLO un JSON válido con esta estructura exacta:
{
  "hook": "Primera frase gancho (primeros 3 segundos, que detenga el scroll)",
  "script": "El guion completo que leerá el avatar, incluyendo el hook al inicio. Solo texto hablado, sin indicaciones de escena.",
  "cta": "Llamada a la acción al final (breve, directa)",
  "caption": "Caption para Instagram (2-3 oraciones atractivas)",
  "hashtags": "#hashtag1 #hashtag2 #hashtag3 (10-15 hashtags relevantes)",
  "estimated_duration_seconds": ${durationSeconds}
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as Omit<ScriptOutput, "topic">;
  logger.info({ topic }, "Script generated by AI");
  return { topic, ...parsed };
}

export interface ContentPlanTopic {
  topic: string;
  scheduled_at: string;
}

export async function generateContentTopics(
  niche: string,
  keywords: string[],
  tone: string,
  language: string,
  days: number,
  postsPerDay: number,
  topPerformingTopics: string[] = []
): Promise<ContentPlanTopic[]> {
  const client = getClient();
  const total = days * postsPerDay;

  const prompt = `Eres un estratega de contenido para Instagram Reels.

Genera un plan de contenido con ${total} temas únicos para el siguiente nicho:
- Nicho: ${niche}
- Palabras clave principales: ${keywords.join(", ")}
- Tono de comunicación: ${tone}
- Idioma: ${language}
- Temas que funcionaron bien antes: ${topPerformingTopics.slice(0, 5).join(", ") || "N/A"}

Reglas:
- Los temas deben ser variados: tips prácticos, educativos, inspiracionales, trending
- Cada tema debe ser específico y accionable, no genérico
- Alternar entre diferentes formatos: "cómo hacer X", "error que cometes con X", "secreto de X", etc.
- Los temas deben programarse a lo largo de ${days} días

Devuelve SOLO un JSON válido con esta estructura:
{
  "topics": [
    {
      "topic": "Título del tema específico",
      "days_from_now": 0
    }
  ]
}

Genera exactamente ${total} temas.`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as { topics: Array<{ topic: string; days_from_now: number }> };
  const now = new Date();

  return parsed.topics.map((t) => {
    const date = new Date(now);
    date.setDate(date.getDate() + t.days_from_now);
    date.setHours(9, 0, 0, 0);
    return { topic: t.topic, scheduled_at: date.toISOString() };
  });
}

export async function analyzeAuditAndRecommend(
  niche: string,
  topPostCaptions: string[],
  avgEngagement: number,
  language: string
): Promise<{ recommended_topics: string[]; content_insights: string; best_posting_times: string[] }> {
  const client = getClient();

  const prompt = `Analiza el rendimiento de una cuenta de Instagram y genera recomendaciones.

Nicho: ${niche}
Idioma: ${language}
Engagement promedio: ${avgEngagement.toFixed(2)}%
Mejores captions/temas de los últimos posts:
${topPostCaptions.slice(0, 10).map((c, i) => `${i + 1}. ${c?.substring(0, 100) || "Sin caption"}`).join("\n")}

Devuelve SOLO un JSON válido:
{
  "recommended_topics": ["tema 1", "tema 2", "tema 3", "tema 4", "tema 5"],
  "content_insights": "2-3 oraciones con insights clave sobre qué tipo de contenido funciona mejor",
  "best_posting_times": ["09:00", "18:00", "21:00"]
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty AI response");
  return JSON.parse(content);
}
