import OpenAI from "openai";
import { logger } from "./logger";

function getClient(): OpenAI {
  return new OpenAI({
    baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
    apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  });
}

export interface ScriptOutput {
  topic: string;
  hook: string;
  script: string;
  cta: string;
  caption: string;
  hashtags: string;
  estimated_duration_seconds: number;
}

export async function generateScript(
  topic: string,
  niche: string,
  tone: string,
  language: string,
  durationSeconds: number
): Promise<ScriptOutput> {
  const client = getClient();
  const wordCount = Math.round((durationSeconds / 60) * 130); // ~130 wpm for video

  const prompt = `Eres un experto en creación de contenido para Instagram Reels.

Crea un guion de video para un Reel de Instagram con estas especificaciones:
- Nicho: ${niche}
- Tema: ${topic}
- Tono: ${tone}
- Idioma: ${language}
- Duración aproximada: ${durationSeconds} segundos (~${wordCount} palabras)

REGLAS OBLIGATORIAS para el campo "script":
1. El guion DEBE terminar con una llamada a la acción clara y directa hablada por el avatar (ej: "Seguime para más tips como este", "Guardá este video y ponelo en práctica hoy", "Comentá abajo si te pasó esto").
2. La ÚLTIMA oración del guion SIEMPRE debe ser: "Este video fue creado con inteligencia artificial. Seguime para más contenido como este." — exactamente así, integrado de forma natural en el cierre.
3. El hook debe ser la primera frase del guion (ya incluida dentro de "script").
4. Sin indicaciones de escena, sin corchetes, sin asteriscos — solo texto hablado corrido.
5. El tono debe sentirse conversacional, no como un comercial.

Devuelve SOLO un JSON válido con esta estructura exacta:
{
  "hook": "Primera frase gancho (primeros 3 segundos, que detenga el scroll)",
  "script": "El guion completo que leerá el avatar. Debe incluir: hook al inicio → desarrollo → CTA hablado → divulgación IA al final.",
  "cta": "La llamada a la acción principal (la misma que está dentro del script, extraída aquí brevemente)",
  "caption": "Caption para Instagram (2-3 oraciones atractivas que complementen el video)",
  "hashtags": "#hashtag1 #hashtag2 #hashtag3 (10-15 hashtags relevantes y específicos al tema)",
  "estimated_duration_seconds": ${durationSeconds}
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as Omit<ScriptOutput, "topic">;
  logger.info({ topic }, "Script generated by AI");
  return { topic, ...parsed };
}

export interface ContentPlanTopic {
  topic: string;
  scheduled_at: string;
}

// Topic categories for a varied, high-performing content mix
const TOPIC_CATEGORIES = `
Distribuye los temas en estas proporciones aproximadas:
  - 35% EVERGREEN: tips prácticos y accionables que siempre son útiles
  - 30% TRENDING/NOTICIAS: temas que reaccionan a cambios recientes en el nicho (actualizaciones de algoritmos de Instagram/TikTok 2025-2026, nuevas funciones de IA, cambios en plataformas de ecommerce, reportes de tendencias del sector)
  - 20% EDUCACIONAL: explicaciones de conceptos, comparaciones, "qué es X y cómo usarlo"
  - 15% SOCIAL PROOF / CASO DE USO: resultados reales, errores comunes, mitos vs realidades

Formatos a alternar (no repetir el mismo más de 3 veces seguidas):
  - "El mayor error que cometen [audiencia] con [X]"
  - "Por qué [plataforma/herramienta] cambió todo para [nicho] en 2025"
  - "Lo que nadie te dice sobre [X]"
  - "Cómo [beneficio específico] en menos de [tiempo]"
  - "ChatGPT / IA para [tarea específica del nicho]: guía rápida"
  - "La actualización de [plataforma] que [audiencia] necesita conocer"
  - "Mito vs realidad: [creencia común del nicho]"
  - "[Número] señales de que tu [X] está funcionando"
  - "El secreto detrás de [resultado que la audiencia quiere]"
  - "Esto que hacías antes ya no funciona — hacé esto en cambio"
`.trim();

export async function generateContentTopics(
  niche: string,
  keywords: string[],
  tone: string,
  language: string,
  days: number,
  postsPerDay: number,
  topPerformingTopics: string[] = []
): Promise<ContentPlanTopic[]> {
  const client = getClient();
  const total = days * postsPerDay;

  // Derive content pillars from the niche string so the AI spreads topics
  // evenly instead of fixating on a single keyword.
  // E.g. "Marketing digital, automatizaciones, chatbot, IA" → 4 pillars
  const rawPillars = niche
    .split(/[,;|]/)
    .map((p) => p.trim())
    .filter((p) => p.length > 2);

  // Also include extra keywords that aren't already covered by pillars
  const extraKeywords = keywords.filter(
    (k) => !rawPillars.some((p) => p.toLowerCase().includes(k.toLowerCase()))
  );
  const allPillars = [...rawPillars, ...extraKeywords];

  const maxPerPillar = Math.ceil(total / Math.max(allPillars.length, 1));

  const prompt = `Eres un estratega de contenido para Instagram Reels especializado en crecimiento orgánico.

Genera un plan de contenido con ${total} temas únicos para el siguiente nicho:
- Nicho: ${niche}
- Tono de comunicación: ${tone}
- Idioma: ${language}
- Temas que ya existen (NO repetir ni parafrasear): ${topPerformingTopics.slice(0, 8).join(" | ") || "N/A"}

PILARES DE CONTENIDO — distribuí los ${total} temas equitativamente entre todos estos pilares.
Cada pilar puede tener como máximo ${maxPerPillar} temas. No pongas más de 2 temas seguidos del mismo pilar:
${allPillars.map((p, i) => `  ${i + 1}. ${p}`).join("\n")}

REGLA CRÍTICA DE VARIEDAD: Aunque un pilar sea "chatbot" o "automatizaciones", los temas dentro de él deben ser distintos entre sí — diferentes ángulos, problemas, audiencias, plataformas. Ejemplos de ángulos para variar:
  - Para el usuario (el dueño del negocio): "cómo implementar X", "errores al configurar X"
  - Para el cliente final: "por qué las empresas usan X", "qué esperar cuando X te atiende"
  - Comparativas: "X vs Y — cuál conviene para tu negocio"
  - Noticias/tendencias: "qué cambió en X en 2025", "la nueva función de X que cambia todo"
  - Resultados: "cuánto ahorra una empresa con X", "caso real: empresa que implementó X"

${TOPIC_CATEGORIES}

Reglas adicionales:
- Cada tema debe ser específico — evitar títulos genéricos como "Tips de marketing"
- Los temas TRENDING deben referenciar contexto actual: algoritmos 2025-2026, IA generativa, cambios en plataformas (Instagram, WhatsApp Business, Shopify, etc.)
- Cada tema debe poder desarrollarse en un Reel de 45-75 segundos
- Los temas deben distribuirse a lo largo de ${days} días, máximo ${postsPerDay} por día

Devuelve SOLO un JSON válido con esta estructura:
{
  "topics": [
    {
      "topic": "Título del tema específico",
      "days_from_now": 0,
      "pillar": "nombre del pilar",
      "category": "evergreen|trending|educacional|social_proof"
    }
  ]
}

Genera exactamente ${total} temas.`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty response from AI");

  const parsed = JSON.parse(content) as { topics: Array<{ topic: string; days_from_now: number; category?: string }> };
  const now = new Date();

  return parsed.topics.map((t) => {
    const date = new Date(now);
    date.setDate(date.getDate() + t.days_from_now);
    date.setHours(9, 0, 0, 0);
    return { topic: t.topic, scheduled_at: date.toISOString() };
  });
}

export async function analyzeAuditAndRecommend(
  niche: string,
  topPostCaptions: string[],
  avgEngagement: number,
  language: string
): Promise<{ recommended_topics: string[]; content_insights: string; best_posting_times: string[] }> {
  const client = getClient();

  const prompt = `Analiza el rendimiento de una cuenta de Instagram y genera recomendaciones.

Nicho: ${niche}
Idioma: ${language}
Engagement promedio: ${avgEngagement.toFixed(2)}%
Mejores captions/temas de los últimos posts:
${topPostCaptions.slice(0, 10).map((c, i) => `${i + 1}. ${c?.substring(0, 100) || "Sin caption"}`).join("\n")}

Devuelve SOLO un JSON válido:
{
  "recommended_topics": ["tema 1", "tema 2", "tema 3", "tema 4", "tema 5"],
  "content_insights": "2-3 oraciones con insights clave sobre qué tipo de contenido funciona mejor",
  "best_posting_times": ["09:00", "18:00", "21:00"]
}`;

  const res = await client.chat.completions.create({
    model: "gpt-5.6-luna",
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
  });

  const content = res.choices[0]?.message?.content;
  if (!content) throw new Error("Empty AI response");
  return JSON.parse(content);
}
