/**
 * B-Roll Engine — AI-generated photorealistic vertical images composited
 * onto the video at script-driven moments, before caption compositing.
 *
 * Pipeline position:
 *   [zoom pre-pass] → [B-roll overlay] → [caption compositing]
 *
 * Each B-roll image is:
 *   • Generated by gpt-image-1 at 1024×1536 (portrait 2:3, scaled/cropped to video 9:16)
 *   • Guided by a per-video visual direction (shared lighting, palette, atmosphere)
 *   • Selected for scroll-stopping impact, not literal illustration
 *   • Animated with a Ken Burns variant (zoom-in / zoom-out / pan-right / pan-left)
 *   • Duration varies per segment based on sentence length (2.5 – 4.5 s)
 *   • Faded in (0.3 s) and out (0.3 s) over the avatar video
 *
 * Graceful degradation: any per-segment failure is skipped; if all fail
 * or there are no assets to composite, the source video is returned unchanged.
 */

import fs from "fs/promises";
import path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import { makeOpenAIClient } from "./openai-client";
import { logger } from "./logger";
import type { PunchWordTiming } from "./caption-engine";

const execFileAsync = promisify(execFile);

// ── Types ────────────────────────────────────────────────────────────────────

export interface BRollSegment {
  /** Start time in seconds within the video */
  startSec: number;
  /** Hold duration in seconds (not counting fade in/out) */
  durationSec: number;
  /** English image generation prompt — concise, cinematic, impact-first */
  imagePrompt: string;
}

export interface BRollImageAsset {
  segment: BRollSegment;
  /** Absolute path to the downloaded PNG on disk */
  tmpPath: string;
}

/** Optional caller-supplied context for richer visual direction generation. */
export interface BRollVisualContext {
  niche?: string | null;
  topic?: string | null;
}

// ── Constants ────────────────────────────────────────────────────────────────

const FADE_DUR        = 0.3;   // seconds for fade in and fade out
const MIN_GAP_SEC     = 10;    // minimum gap between B-roll segments
const MIN_START_SEC   = 4;     // don't start in the first N seconds (hook / opening)
const MIN_END_MARGIN  = 5;     // don't start within last N seconds

/**
 * Safety suffix appended to every image prompt.
 * People and human subjects are ALLOWED — only text/logos are excluded.
 */
const PHOTO_SAFETY_SUFFIX =
  "9:16 portrait vertical photograph, ultra-detailed, professional photography. " +
  "No text overlays, no watermarks, no brand logos, no recognizable trademarks. " +
  "Anonymous people and human subjects are allowed when natural to the scene. ";

/** Count of B-roll segments scaled to video duration */
function bRollCount(durationSec: number): number {
  if (durationSec < 45) return 2;
  if (durationSec < 90) return 3;
  return 4;
}

/** Estimate hold duration from sentence complexity (word count). */
function estimateHoldDuration(sentence: string): number {
  const wordCount = sentence.split(/\s+/).filter((w) => w.length > 0).length;
  if (wordCount <= 8)  return 2.5; // short sentence — quick cut
  if (wordCount <= 14) return 3.5; // medium sentence
  return 4.5;                       // long/dense sentence — more time to absorb
}

// ── Step 0: Visual direction generation ──────────────────────────────────────

/**
 * Generate a one-time cinematographic brief for the entire video.
 * All B-roll images in this video share this visual direction for coherence.
 * Returns empty string on any failure (caller uses a generic fallback).
 */
async function generateVisualDirection(
  visualSuggestions: string | null,
  visualContext?: BRollVisualContext | null,
  openaiApiKey?: string | null,
): Promise<string> {
  try {
    const client = makeOpenAIClient(openaiApiKey, { timeout: 30_000 });

    const contextLines = [
      visualContext?.niche  ? `Niche: ${visualContext.niche}` : "",
      visualContext?.topic  ? `Topic: ${visualContext.topic}` : "",
      visualSuggestions     ? `Visual context: ${visualSuggestions}` : "",
    ].filter(Boolean).join("\n");

    if (!contextLines) return "";

    const { choices } = await client.chat.completions.create({
      model: "gpt-5.4-mini",
      temperature: 0.8,
      max_tokens: 120,
      messages: [
        {
          role: "system",
          content:
            "You are a cinematographer directing Instagram Reels. " +
            "Write a concise visual direction in 1–2 English sentences. " +
            "Specify: lighting mood, color temperature, atmosphere, and photographic style. " +
            "Make it striking and scroll-stopping. Reply ONLY with the visual direction text, no labels.",
        },
        {
          role: "user",
          content:
            contextLines +
            "\n\nGenerate a cohesive cinematographic visual direction so that every B-roll image " +
            "in this video feels intentional and visually consistent. " +
            "Think: what lighting and atmosphere would make a viewer stop scrolling?",
        },
      ],
    });

    const result = choices[0]?.message?.content?.trim() ?? "";
    logger.info({ result: result.slice(0, 80) }, "[BRoll] Visual direction generated");
    return result;
  } catch (err) {
    logger.warn({ err }, "[BRoll] Visual direction generation failed — using prompt-only images");
    return "";
  }
}

// ── Step 1: Segment analysis ─────────────────────────────────────────────────

interface RawAISegment {
  sentenceIdx: number;
  imagePrompt: string;
}

/**
 * Ask GPT-4o-mini to select which sentences deserve B-roll and what to show.
 * Prioritizes scroll-stopping impact over literal illustration.
 */
async function analyzeScriptForBRoll(
  sentences: string[],
  count: number,
  visualSuggestions: string | null,
  openaiApiKey?: string | null,
): Promise<RawAISegment[]> {
  if (count <= 0 || sentences.length === 0) return [];

  const client = makeOpenAIClient(openaiApiKey, { timeout: 60_000 });

  const cap = Math.min(sentences.length, 50);
  const numbered = sentences.slice(0, cap).map((s, i) => `${i}: ${s}`).join("\n");
  const suggestionsBlock = visualSuggestions
    ? `\nVisual style context for this topic (use as inspiration):\n${visualSuggestions}\n`
    : "";

  const { choices } = await client.chat.completions.create({
    model: "gpt-5.4-mini",
    temperature: 0.7,
    max_tokens: 500,
    messages: [
      {
        role: "system",
        content:
          "You select moments in video scripts for scroll-stopping B-roll images. " +
          "Reply ONLY with a valid JSON array — no markdown, no code block.",
      },
      {
        role: "user",
        content:
          `Select exactly ${count} moments from this script for B-roll images that would stop scrolling.\n\n` +
          `SELECTION CRITERIA — prioritize moments that:\n` +
          `• Represent a peak emotional beat, surprising revelation, or key tension point\n` +
          `• Describe a situation with strong visual potential (human drama, striking contrast, powerful context)\n` +
          `• Are spread across the script — do NOT cluster near the beginning or end\n` +
          `• Are NOT the most predictable or generic lines in the script\n\n` +
          `For each selected moment write a CINEMATOGRAPHIC image prompt that:\n` +
          `• Describes a scene designed to STOP scrolling — dramatic, atmospheric, or emotionally resonant\n` +
          `• Uses strong composition (depth, contrast, foreground/background, leading lines)\n` +
          `• Specifies mood, lighting, and atmosphere — not just subject matter\n` +
          `• Can include anonymous people in authentic situations when natural\n` +
          `• Is specific and visual — NOT a literal illustration of the spoken words\n` +
          `• Is written in English\n` +
          suggestionsBlock +
          `\nScript sentences (numbered):\n${numbered}\n\n` +
          `Reply with ONLY a JSON array of exactly ${count} objects:\n` +
          `[{"sentenceIdx": <number>, "imagePrompt": "<english cinematic prompt>"}, ...]`,
      },
    ],
  });

  const raw = choices[0]?.message?.content?.trim() ?? "[]";
  const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/, "");

  let parsed: unknown[];
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    logger.warn({ raw }, "[BRoll] AI response not valid JSON — skipping");
    return [];
  }

  return (parsed as RawAISegment[])
    .filter(
      (x): x is RawAISegment =>
        typeof x === "object" &&
        x !== null &&
        typeof x.sentenceIdx === "number" &&
        Number.isInteger(x.sentenceIdx) &&
        x.sentenceIdx >= 0 &&
        x.sentenceIdx < cap &&
        typeof x.imagePrompt === "string" &&
        x.imagePrompt.length > 5,
    )
    .slice(0, count);
}

/**
 * Map a sentence index to its best SRT timestamp using the same closest-match
 * proportional technique as the punch zoom engine.
 */
function sentenceToTimestamp(
  sentences: string[],
  idx: number,
  wordTimings: PunchWordTiming[],
  totalChars: number,
  videoDuration: number,
): number | null {
  const sentence = sentences[idx];
  if (!sentence) return null;

  const sentenceStart = sentences.slice(0, idx).reduce((s, x) => s + x.length, 0);
  const expectedMs = (sentenceStart / totalChars) * videoDuration * 1000;
  const windowMs = videoDuration * 350; // ±35 % window

  const candidates = sentence
    .replace(/[^a-záéíóúüñA-ZÁÉÍÓÚÜÑ0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 2)
    .slice(0, 6);

  let bestHit: PunchWordTiming | null = null;
  let bestDist = Infinity;

  for (const word of candidates) {
    const norm = word.toLowerCase().replace(/[^a-záéíóúüñ0-9]/g, "");
    for (const wt of wordTimings) {
      if (wt.text.toLowerCase().replace(/[^a-záéíóúüñ0-9]/g, "") !== norm) continue;
      const dist = Math.abs(wt.startMs - expectedMs);
      if (dist < windowMs && dist < bestDist) {
        bestDist = dist;
        bestHit = wt;
      }
    }
  }

  if (bestHit) {
    const t = bestHit.startMs / 1000;
    return t >= MIN_START_SEC && t < videoDuration - MIN_END_MARGIN ? t : null;
  }

  const t = expectedMs / 1000;
  return t >= MIN_START_SEC && t < videoDuration - MIN_END_MARGIN ? t : null;
}

/**
 * Analyze the script and return timed B-roll segments with image prompts.
 * Generates a shared visual direction first, then selects moments.
 */
export async function analyzeBRollSegments(
  script: string,
  wordTimings: PunchWordTiming[],
  videoDuration: number,
  visualSuggestions?: string | null,
  openaiApiKey?: string | null,
  visualContext?: BRollVisualContext | null,
): Promise<{ segments: BRollSegment[]; visualDirection: string }> {
  const count = bRollCount(videoDuration);

  const sentences = (script.match(/[^.!?\n]+[.!?]*/g) ?? [])
    .map((s) => s.trim())
    .filter((s) => s.length >= 12);

  if (sentences.length < 3) {
    logger.warn({ sentenceCount: sentences.length }, "[BRoll] Script too short for B-roll analysis");
    return { segments: [], visualDirection: "" };
  }

  const totalChars = sentences.reduce((s, x) => s + x.length, 0) || 1;

  // Generate shared visual direction for this video
  const visualDirection = await generateVisualDirection(
    visualSuggestions ?? null,
    visualContext,
    openaiApiKey,
  );

  // Skip first 2 sentences (hook) — same convention as punch zoom
  const bodyStart = Math.min(2, sentences.length - 1);
  const bodySentences = sentences.slice(bodyStart);

  let rawSegments: RawAISegment[] = [];
  try {
    rawSegments = await analyzeScriptForBRoll(bodySentences, count, visualSuggestions ?? null, openaiApiKey);
    logger.info({ count: rawSegments.length }, "[BRoll] AI selected segments");
  } catch (err) {
    logger.warn({ err }, "[BRoll] AI analysis failed — no B-roll");
    return { segments: [], visualDirection };
  }

  // Map sentence indices to timestamps (adjust for bodyStart offset)
  const segments: BRollSegment[] = [];
  for (const raw of rawSegments) {
    const globalIdx = raw.sentenceIdx + bodyStart;
    const startSec = sentenceToTimestamp(sentences, globalIdx, wordTimings, totalChars, videoDuration);
    if (startSec === null) continue;
    segments.push({
      startSec,
      durationSec: estimateHoldDuration(sentences[globalIdx] ?? ""),
      imagePrompt: raw.imagePrompt,
    });
  }

  // Sort by time, then enforce minimum gap between segments
  segments.sort((a, b) => a.startSec - b.startSec);
  const result: BRollSegment[] = [];
  for (const seg of segments) {
    if (result.length === 0) {
      result.push(seg);
      continue;
    }
    const prev = result[result.length - 1];
    if (seg.startSec - (prev.startSec + prev.durationSec) >= MIN_GAP_SEC) {
      result.push(seg);
    }
  }

  logger.info(
    { segments: result.map((s) => ({ startSec: s.startSec, dur: s.durationSec, prompt: s.imagePrompt.slice(0, 60) })) },
    "[BRoll] Final segments",
  );
  return { segments: result, visualDirection };
}

// ── Step 2: Image generation ─────────────────────────────────────────────────

/**
 * Generate a B-roll image for each segment using gpt-image-1 at 1024×1536.
 * The full prompt = [visualDirection + ". "] + PHOTO_SAFETY_SUFFIX + segment.imagePrompt
 * Images are saved to tmpDir as PNG files.
 * Individual failures are logged and skipped — does not throw.
 */
export async function generateBRollImages(
  segments: BRollSegment[],
  tmpDir: string,
  visualDirection: string,
  openaiApiKey?: string | null,
): Promise<BRollImageAsset[]> {
  const client = makeOpenAIClient(openaiApiKey, { timeout: 120_000 });

  const results: BRollImageAsset[] = [];
  const directionPrefix = visualDirection ? `${visualDirection}. ` : "";

  // Generate sequentially to avoid hammering the API
  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    const prompt = directionPrefix + PHOTO_SAFETY_SUFFIX + segment.imagePrompt;

    try {
      logger.info(
        { idx: i, prompt: prompt.slice(0, 100) },
        "[BRoll] Generating image...",
      );

      const response = await (client.images.generate as unknown as (
        body: Record<string, unknown>
      ) => Promise<{ data?: Array<{ b64_json?: string }> }>)({
        model: "gpt-image-1",
        prompt,
        size: "1024x1536",
        quality: "high",
      });

      const b64 = response.data?.[0]?.b64_json;
      if (!b64) {
        logger.warn({ idx: i }, "[BRoll] No image data returned — skipping segment");
        continue;
      }

      const tmpPath = path.join(tmpDir, `broll_${i}.png`);
      await fs.writeFile(tmpPath, Buffer.from(b64, "base64"));
      results.push({ segment, tmpPath });
      logger.info({ idx: i, path: tmpPath }, "[BRoll] Image generated ✓");
    } catch (err) {
      logger.warn({ idx: i, err }, "[BRoll] Image generation failed — skipping segment");
    }
  }

  return results;
}

// ── Step 3: FFmpeg compositing with Ken Burns ─────────────────────────────────

/**
 * Composite B-roll images onto the source video.
 *
 * Each image:
 *   • Is scaled+cropped to exact video dimensions (center crop)
 *   • Is converted to yuva420p (alpha channel required for fade)
 *   • Fades in over FADE_DUR seconds, holds, then fades out over FADE_DUR seconds
 *   • Is overlaid on top of the base video during its time window
 *   • Audio track is copied unchanged
 *
 * Note: zoompan (Ken Burns) is intentionally avoided — it is broken in FFmpeg 6.1.2
 * via execFile and causes silent compositing failures. Simple scale+crop is reliable.
 *
 * Returns the path to the composited video, or sourcePath if compositing failed.
 */
export async function composeBRoll(
  sourcePath: string,
  assets: BRollImageAsset[],
  videoWidth: number,
  videoHeight: number,
  videoDuration: number,
  tmpDir: string,
): Promise<string> {
  if (assets.length === 0) return sourcePath;

  const outputPath = path.join(tmpDir, "broll_composited.mp4");

  // Build input args: one -loop 1 -t <duration> -i <path> per image
  const inputArgs: string[] = [];
  for (const asset of assets) {
    inputArgs.push("-loop", "1", "-t", String(Math.ceil(videoDuration + 1)), "-i", asset.tmpPath);
  }

  // Build filter_complex — simple scale+crop (no zoompan; zoompan is broken in FFmpeg 6.1.2 via execFile)
  const filterParts: string[] = [];
  let prevLabel = "[0:v]";

  for (let i = 0; i < assets.length; i++) {
    const { segment } = assets[i];
    const inputIdx = i + 1; // [0] is the source video
    const bvLabel  = `[bv${i}]`;
    const outLabel = i === assets.length - 1 ? "[vout]" : `[ov${i}]`;

    const fadeInSt  = segment.startSec.toFixed(3);
    const fadeOutSt = Math.max(
      segment.startSec + FADE_DUR,
      segment.startSec + segment.durationSec - FADE_DUR,
    ).toFixed(3);

    filterParts.push(
      `[${inputIdx}:v]` +
        // 1. Scale to cover exact video dims, then center-crop
        `scale=${videoWidth}:${videoHeight}:force_original_aspect_ratio=increase,` +
        `crop=${videoWidth}:${videoHeight},` +
        `setsar=1,` +
        // 2. Alpha channel for fade
        `format=yuva420p,` +
        // 3. Fade in / out
        `fade=t=in:st=${fadeInSt}:d=${FADE_DUR}:alpha=1,` +
        `fade=t=out:st=${fadeOutSt}:d=${FADE_DUR}:alpha=1` +
        `${bvLabel}`,
    );
    filterParts.push(`${prevLabel}${bvLabel}overlay=0:0:eof_action=pass${outLabel}`);
    prevLabel = outLabel;
  }

  const filterComplex = filterParts.join(";");

  logger.info(
    { assetCount: assets.length, videoWidth, videoHeight, videoDuration },
    "[BRoll] Running FFmpeg B-roll compositing...",
  );

  try {
    await execFileAsync(
      "ffmpeg",
      [
        "-i", sourcePath,
        ...inputArgs,
        "-filter_complex", filterComplex,
        "-map", "[vout]",
        "-map", "0:a",
        "-c:v", "libx264", "-preset", "fast", "-crf", "21",
        "-c:a", "copy",
        "-movflags", "+faststart",
        "-y", outputPath,
      ],
      { maxBuffer: 500 * 1024 * 1024 },
    );

    logger.info({ outputPath }, "[BRoll] B-roll compositing done ✓");
    return outputPath;
  } catch (err) {
    logger.warn({ err }, "[BRoll] FFmpeg compositing failed — returning source video unchanged");
    return sourcePath;
  }
}

// ── Convenience: full B-roll pipeline ────────────────────────────────────────

/**
 * Run the full B-roll pipeline: analyze → generate → composite.
 * Returns the composited video path, or sourcePath on any unrecoverable failure.
 *
 * @param visualContext  Optional niche/topic context for richer visual direction.
 *   Existing callers that omit this param continue to work unchanged.
 */
export async function applyBRoll(
  sourcePath: string,
  script: string,
  wordTimings: PunchWordTiming[],
  videoWidth: number,
  videoHeight: number,
  videoDuration: number,
  tmpDir: string,
  visualSuggestions?: string | null,
  openaiApiKey?: string | null,
  visualContext?: BRollVisualContext | null,
): Promise<string> {
  try {
    const { segments, visualDirection } = await analyzeBRollSegments(
      script,
      wordTimings,
      videoDuration,
      visualSuggestions,
      openaiApiKey,
      visualContext,
    );
    if (segments.length === 0) {
      logger.info("[BRoll] No segments to composite — skipping");
      return sourcePath;
    }

    const assets = await generateBRollImages(segments, tmpDir, visualDirection, openaiApiKey);
    if (assets.length === 0) {
      logger.info("[BRoll] No images generated — skipping compositing");
      return sourcePath;
    }

    return await composeBRoll(sourcePath, assets, videoWidth, videoHeight, videoDuration, tmpDir);
  } catch (err) {
    logger.warn({ err }, "[BRoll] B-roll pipeline failed — returning source video unchanged");
    return sourcePath;
  }
}
