/**
 * B-Roll Engine — AI-generated photorealistic vertical images composited
 * onto the video at script-driven moments, before caption compositing.
 *
 * Pipeline position:
 *   [zoom pre-pass] → [B-roll overlay] → [caption compositing]
 *
 * Each B-roll image is:
 *   • Generated by gpt-image-1 at 1024×1536 (portrait 2:3, scaled/cropped to video 9:16)
 *   • Scaled to the actual video dimensions with object-fit:cover crop
 *   • Faded in (0.3 s) and out (0.3 s) over the avatar video
 *   • Placed at the most visually-appropriate moments in the script
 *
 * Graceful degradation: any per-segment failure is skipped; if all fail
 * or there are no assets to composite, the source video is returned unchanged.
 */

import fs from "fs/promises";
import path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import { makeOpenAIClient } from "./openai-client";
import { logger } from "./logger";
import type { PunchWordTiming } from "./caption-engine";

const execFileAsync = promisify(execFile);

// ── Types ────────────────────────────────────────────────────────────────────

export interface BRollSegment {
  /** Start time in seconds within the video */
  startSec: number;
  /** Hold duration in seconds (not counting fade in/out) */
  durationSec: number;
  /** English image generation prompt — concise, visual, no text/people */
  imagePrompt: string;
}

export interface BRollImageAsset {
  segment: BRollSegment;
  /** Absolute path to the downloaded PNG on disk */
  tmpPath: string;
}

// ── Constants ────────────────────────────────────────────────────────────────

const FADE_DUR = 0.3; // seconds for fade in and fade out
const SEGMENT_HOLD = 3.5; // default hold duration (seconds)
const MIN_GAP_SEC = 10; // minimum gap between B-roll segments
const MIN_START_SEC = 4; // don't start in the first N seconds (hook / opening)
const MIN_END_MARGIN = 5; // don't start within last N seconds

/** Count of B-roll segments scaled to video duration */
function bRollCount(durationSec: number): number {
  if (durationSec < 45) return 2;
  if (durationSec < 90) return 3;
  return 4;
}

// ── Step 1: Segment analysis ─────────────────────────────────────────────────

interface RawAISegment {
  sentenceIdx: number;
  imagePrompt: string;
}

/**
 * Ask GPT-4o-mini to select which sentences need B-roll and what to show.
 * Receives the numbered sentence list (post-hook sentences only) and
 * optional visual-support suggestions already generated for the topic.
 */
async function analyzeScriptForBRoll(
  sentences: string[],
  count: number,
  visualSuggestions: string | null,
  openaiApiKey?: string | null,
): Promise<RawAISegment[]> {
  if (count <= 0 || sentences.length === 0) return [];

  const client = makeOpenAIClient(openaiApiKey, { timeout: 60_000 });

  const cap = Math.min(sentences.length, 50);
  const numbered = sentences.slice(0, cap).map((s, i) => `${i}: ${s}`).join("\n");
  const suggestionsBlock = visualSuggestions
    ? `\nVisual context for this topic (use as inspiration):\n${visualSuggestions}\n`
    : "";

  const { choices } = await client.chat.completions.create({
    model: "gpt-4o-mini",
    temperature: 0,
    max_tokens: 400,
    messages: [
      {
        role: "system",
        content:
          "You choose moments in video scripts where a B-roll image should appear to visually reinforce the message. " +
          "Reply ONLY with a valid JSON array — no markdown, no code block.",
      },
      {
        role: "user",
        content:
          `From the numbered sentences below, select exactly ${count} moments where showing a relevant background image would enhance the content.\n` +
          `Rules:\n` +
          `• Spread selections — do not cluster all near the beginning or end.\n` +
          `• Choose moments that describe a concrete concept, fact, place, object, or action — NOT abstract emotions.\n` +
          `• For each moment write a concise English image prompt: photorealistic scene, no people, no text.\n` +
          `• Prompts must be specific and visual (e.g. "Modern laptop on wooden desk with a cup of coffee, warm morning light" not "productivity").\n` +
          `• Prompts must be safe, appropriate, and not include brand names.\n` +
          suggestionsBlock +
          `\nSentences:\n${numbered}\n\n` +
          `Reply with ONLY a JSON array of exactly ${count} objects:\n` +
          `[{"sentenceIdx": <number>, "imagePrompt": "<english prompt>"}, ...]`,
      },
    ],
  });

  const raw = choices[0]?.message?.content?.trim() ?? "[]";
  // Strip markdown code fences if present
  const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/, "");

  let parsed: unknown[];
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    logger.warn({ raw }, "[BRoll] AI response not valid JSON — skipping");
    return [];
  }

  return (parsed as RawAISegment[])
    .filter(
      (x): x is RawAISegment =>
        typeof x === "object" &&
        x !== null &&
        typeof x.sentenceIdx === "number" &&
        Number.isInteger(x.sentenceIdx) &&
        x.sentenceIdx >= 0 &&
        x.sentenceIdx < cap &&
        typeof x.imagePrompt === "string" &&
        x.imagePrompt.length > 5,
    )
    .slice(0, count);
}

/**
 * Map a sentence index to its best SRT timestamp using the same closest-match
 * proportional technique as the punch zoom engine.
 */
function sentenceToTimestamp(
  sentences: string[],
  idx: number,
  wordTimings: PunchWordTiming[],
  totalChars: number,
  videoDuration: number,
): number | null {
  const sentence = sentences[idx];
  if (!sentence) return null;

  const sentenceStart = sentences.slice(0, idx).reduce((s, x) => s + x.length, 0);
  const expectedMs = (sentenceStart / totalChars) * videoDuration * 1000;
  const windowMs = videoDuration * 350; // ±35 % window

  const candidates = sentence
    .replace(/[^a-záéíóúüñA-ZÁÉÍÓÚÜÑ0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 2)
    .slice(0, 6);

  let bestHit: PunchWordTiming | null = null;
  let bestDist = Infinity;

  for (const word of candidates) {
    const norm = word.toLowerCase().replace(/[^a-záéíóúüñ0-9]/g, "");
    for (const wt of wordTimings) {
      if (wt.text.toLowerCase().replace(/[^a-záéíóúüñ0-9]/g, "") !== norm) continue;
      const dist = Math.abs(wt.startMs - expectedMs);
      if (dist < windowMs && dist < bestDist) {
        bestDist = dist;
        bestHit = wt;
      }
    }
  }

  if (bestHit) {
    const t = bestHit.startMs / 1000;
    return t >= MIN_START_SEC && t < videoDuration - MIN_END_MARGIN ? t : null;
  }

  const t = expectedMs / 1000;
  return t >= MIN_START_SEC && t < videoDuration - MIN_END_MARGIN ? t : null;
}

/**
 * Analyze the script and return timed B-roll segments with image prompts.
 * Uses GPT to select sentences and map them to SRT timestamps.
 */
export async function analyzeBRollSegments(
  script: string,
  wordTimings: PunchWordTiming[],
  videoDuration: number,
  visualSuggestions?: string | null,
  openaiApiKey?: string | null,
): Promise<BRollSegment[]> {
  const count = bRollCount(videoDuration);

  const sentences = (script.match(/[^.!?\n]+[.!?]*/g) ?? [])
    .map((s) => s.trim())
    .filter((s) => s.length >= 12);

  if (sentences.length < 3) {
    logger.warn({ sentenceCount: sentences.length }, "[BRoll] Script too short for B-roll analysis");
    return [];
  }

  const totalChars = sentences.reduce((s, x) => s + x.length, 0) || 1;

  // Skip first 2 sentences (hook) — same convention as punch zoom
  const bodyStart = Math.min(2, sentences.length - 1);
  const bodySentences = sentences.slice(bodyStart);

  let rawSegments: RawAISegment[] = [];
  try {
    rawSegments = await analyzeScriptForBRoll(bodySentences, count, visualSuggestions ?? null, openaiApiKey);
    logger.info({ count: rawSegments.length }, "[BRoll] AI selected segments");
  } catch (err) {
    logger.warn({ err }, "[BRoll] AI analysis failed — no B-roll");
    return [];
  }

  // Map sentence indices to timestamps (adjust for bodyStart offset)
  const segments: BRollSegment[] = [];
  for (const raw of rawSegments) {
    const globalIdx = raw.sentenceIdx + bodyStart;
    const startSec = sentenceToTimestamp(sentences, globalIdx, wordTimings, totalChars, videoDuration);
    if (startSec === null) continue;
    segments.push({
      startSec,
      durationSec: SEGMENT_HOLD,
      imagePrompt: raw.imagePrompt,
    });
  }

  // Sort by time, then enforce minimum gap between segments
  segments.sort((a, b) => a.startSec - b.startSec);
  const result: BRollSegment[] = [];
  for (const seg of segments) {
    if (result.length === 0) {
      result.push(seg);
      continue;
    }
    const prev = result[result.length - 1];
    if (seg.startSec - (prev.startSec + prev.durationSec) >= MIN_GAP_SEC) {
      result.push(seg);
    }
  }

  logger.info(
    { segments: result.map((s) => ({ startSec: s.startSec, prompt: s.imagePrompt.slice(0, 60) })) },
    "[BRoll] Final segments",
  );
  return result;
}

// ── Step 2: Image generation ─────────────────────────────────────────────────

const PHOTOREALISM_PREFIX =
  "Photorealistic vertical photograph, ultra-detailed, cinematic natural lighting, " +
  "professional photography, 9:16 portrait aspect ratio, " +
  "no text, no watermarks, no logos, no people, no faces. ";

/**
 * Generate a B-roll image for each segment using gpt-image-1 at 1024×1536 (portrait 2:3).
 * Images are saved to tmpDir as PNG files.
 * Individual failures are logged and skipped — does not throw.
 */
export async function generateBRollImages(
  segments: BRollSegment[],
  tmpDir: string,
  openaiApiKey?: string | null,
): Promise<BRollImageAsset[]> {
  const client = makeOpenAIClient(openaiApiKey, { timeout: 120_000 });

  const results: BRollImageAsset[] = [];

  // Generate sequentially to avoid hammering the API
  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    const prompt = PHOTOREALISM_PREFIX + segment.imagePrompt;

    try {
      logger.info(
        { idx: i, prompt: segment.imagePrompt.slice(0, 80) },
        "[BRoll] Generating image...",
      );

      // gpt-image-1 portrait size: 1024×1536 (2:3). The FFmpeg compositor
      // then scales+crops to the actual video dimensions (e.g. 720×1280 = 9:16).
      // Cast via unknown to bypass the SDK overload union — gpt-image-1 accepts
      // 1024x1536 at runtime but the TS type only lists square sizes.
      const response = await (client.images.generate as unknown as (
        body: Record<string, unknown>
      ) => Promise<{ data?: Array<{ b64_json?: string }> }>)({
        model: "gpt-image-1",
        prompt,
        size: "1024x1536",
        quality: "medium", // "high" for best photorealism at ~2× cost
      });

      const b64 = response.data?.[0]?.b64_json;
      if (!b64) {
        logger.warn({ idx: i }, "[BRoll] No image data returned — skipping segment");
        continue;
      }

      const tmpPath = path.join(tmpDir, `broll_${i}.png`);
      await fs.writeFile(tmpPath, Buffer.from(b64, "base64"));
      results.push({ segment, tmpPath });
      logger.info({ idx: i, path: tmpPath }, "[BRoll] Image generated ✓");
    } catch (err) {
      logger.warn({ idx: i, err }, "[BRoll] Image generation failed — skipping segment");
    }
  }

  return results;
}

// ── Step 3: FFmpeg compositing ───────────────────────────────────────────────

/**
 * Composite B-roll images onto the source video with crossfade transitions.
 *
 * Each image:
 *   • Is scaled to the video dimensions using object-fit:cover (scale+crop)
 *   • Is converted to yuva420p (alpha channel required for fade)
 *   • Fades in over FADE_DUR seconds, holds, then fades out over FADE_DUR seconds
 *   • Is overlaid on top of the base video during its time window
 *   • Audio track is copied unchanged
 *
 * Returns the path to the composited video, or sourcePath if compositing failed.
 */
export async function composeBRoll(
  sourcePath: string,
  assets: BRollImageAsset[],
  videoWidth: number,
  videoHeight: number,
  videoDuration: number,
  tmpDir: string,
): Promise<string> {
  if (assets.length === 0) return sourcePath;

  const outputPath = path.join(tmpDir, "broll_composited.mp4");

  // Build input args: one -loop 1 -t <duration> -i <path> per image
  // Using the full video duration ensures the image stream covers any requested window
  const inputArgs: string[] = [];
  for (const asset of assets) {
    inputArgs.push("-loop", "1", "-t", String(Math.ceil(videoDuration + 1)), "-i", asset.tmpPath);
  }

  // Build filter_complex
  // For each image:
  //   1. Scale with aspect-ratio preserve then crop to exact video dimensions (cover)
  //   2. Convert to yuva420p for alpha support
  //   3. Fade in at startSec (relative to image stream start = video t=0)
  //   4. Fade out at startSec + durationSec - FADE_DUR
  //   5. Overlay on the accumulated video output
  const filterParts: string[] = [];
  let prevLabel = "[0:v]";

  for (let i = 0; i < assets.length; i++) {
    const { segment } = assets[i];
    const inputIdx = i + 1; // [0] is the source video
    const bvLabel = `[bv${i}]`;
    const outLabel = i === assets.length - 1 ? "[vout]" : `[ov${i}]`;

    const fadeInSt = segment.startSec.toFixed(3);
    const fadeOutSt = Math.max(
      segment.startSec + FADE_DUR,
      segment.startSec + segment.durationSec - FADE_DUR,
    ).toFixed(3);

    filterParts.push(
      `[${inputIdx}:v]` +
        `scale=${videoWidth}:${videoHeight}:force_original_aspect_ratio=increase,` +
        `crop=${videoWidth}:${videoHeight},` +
        `setsar=1,` +
        `format=yuva420p,` +
        `fade=t=in:st=${fadeInSt}:d=${FADE_DUR}:alpha=1,` +
        `fade=t=out:st=${fadeOutSt}:d=${FADE_DUR}:alpha=1` +
        `${bvLabel}`,
    );
    filterParts.push(`${prevLabel}${bvLabel}overlay=0:0:eof_action=pass${outLabel}`);
    prevLabel = outLabel;
  }

  const filterComplex = filterParts.join(";");

  logger.info(
    { assetCount: assets.length, videoWidth, videoHeight, videoDuration },
    "[BRoll] Running FFmpeg B-roll compositing...",
  );

  try {
    await execFileAsync(
      "ffmpeg",
      [
        "-i", sourcePath,
        ...inputArgs,
        "-filter_complex", filterComplex,
        "-map", "[vout]",
        "-map", "0:a",
        "-c:v", "libx264", "-preset", "fast", "-crf", "21",
        "-c:a", "copy",
        "-movflags", "+faststart",
        "-y", outputPath,
      ],
      { maxBuffer: 500 * 1024 * 1024 },
    );

    logger.info({ outputPath }, "[BRoll] B-roll compositing done ✓");
    return outputPath;
  } catch (err) {
    logger.warn({ err }, "[BRoll] FFmpeg compositing failed — returning source video unchanged");
    return sourcePath;
  }
}

// ── Convenience: full B-roll pipeline ────────────────────────────────────────

/**
 * Run the full B-roll pipeline: analyze → generate → composite.
 * Returns the composited video path, or sourcePath on any unrecoverable failure.
 */
export async function applyBRoll(
  sourcePath: string,
  script: string,
  wordTimings: PunchWordTiming[],
  videoWidth: number,
  videoHeight: number,
  videoDuration: number,
  tmpDir: string,
  visualSuggestions?: string | null,
  openaiApiKey?: string | null,
): Promise<string> {
  try {
    const segments = await analyzeBRollSegments(
      script,
      wordTimings,
      videoDuration,
      visualSuggestions,
      openaiApiKey,
    );
    if (segments.length === 0) {
      logger.info("[BRoll] No segments to composite — skipping");
      return sourcePath;
    }

    const assets = await generateBRollImages(segments, tmpDir, openaiApiKey);
    if (assets.length === 0) {
      logger.info("[BRoll] No images generated — skipping compositing");
      return sourcePath;
    }

    return await composeBRoll(sourcePath, assets, videoWidth, videoHeight, videoDuration, tmpDir);
  } catch (err) {
    logger.warn({ err }, "[BRoll] B-roll pipeline failed — returning source video unchanged");
    return sourcePath;
  }
}
