// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reelsona-landing/LandingVisual.tsx": () => import("../components/mockups/reelsona-landing/LandingVisual.tsx"),
  "./components/mockups/text-cards-demo/TextCardsDemo.tsx": () => import("../components/mockups/text-cards-demo/TextCardsDemo.tsx")
};
